# Generated by Django 5.2 on 2025-05-06 10:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default='', max_length=255)),
                ('official_name', models.TextField(default='')),
                ('cca2_name', models.CharField(default='', max_length=10, unique=True)),
                ('region', models.CharField(default='', max_length=100)),
                ('subregion', models.CharField(default='', max_length=150)),
                ('capital', models.CharField(default='', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area', models.FloatField()),
                ('population', models.IntegerField()),
                ('flag', models.TextField(default='')),
                ('timezones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('full_response', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
