# Generated by Django 5.2 on 2025-05-07 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_countrydata_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydata',
            name='language',
        ),
        migrations.AddField(
            model_name='countrydata',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
